import { parse, stringify } from 'yaml'

export const RUN_PROVIDER_MODELS = {
  openai: ['gpt-5.1', 'gpt-5.1-codex-max', 'gpt-5.2', 'gpt-5.2-pro', 'gpt-5.2-codex', 'gpt-5.3-codex'],
  anthropic: [
    'claude-sonnet-4',
    'claude-opus-4',
    'claude-sonnet-4.5',
    'claude-haiku-4.5',
    'claude-opus-4.5',
    'claude-sonnet-4.6',
    'claude-opus-4.6',
  ],
} as const

export type RunConfigProvider = keyof typeof RUN_PROVIDER_MODELS

export const RUN_PROVIDERS = Object.keys(RUN_PROVIDER_MODELS) as RunConfigProvider[]
export const RUN_REASONING_EFFORTS = ['minimal', 'low', 'medium', 'high'] as const

export type RunReasoningEffort = (typeof RUN_REASONING_EFFORTS)[number]

const RUN_NAME_PREFIX_WORDS = [
  'amber',
  'brisk',
  'cinder',
  'delta',
  'ember',
  'frost',
  'glint',
  'harbor',
  'ivory',
  'juno',
  'keen',
  'lumen',
  'morrow',
  'nova',
  'onyx',
  'prairie',
] as const

const RUN_NAME_MIDDLE_WORDS = [
  'anchor',
  'beacon',
  'cipher',
  'drift',
  'echo',
  'forge',
  'grove',
  'harvest',
  'index',
  'junction',
  'kernel',
  'ledger',
  'matrix',
  'nimbus',
  'orbit',
  'pulse',
] as const

const RUN_NAME_SUFFIX_WORDS = [
  'atlas',
  'bridge',
  'comet',
  'dock',
  'engine',
  'field',
  'garden',
  'harbor',
  'launch',
  'meadow',
  'node',
  'relay',
  'signal',
  'vault',
  'vector',
  'yard',
] as const

export type RunConfigFormValues = {
  name: string
  systemPromptAppend: string
  prompt: string
  context: string
  llm: {
    provider: RunConfigProvider
    model: string
    reasoning: {
      enabled: boolean
      effort: RunReasoningEffort
    }
  }
  rlm: {
    enabled: boolean
    maxDepth: number
  }
}

type ParsedRunConfigMetadata = {
  maxDepth: number
  name: string
}

type RunConfigYamlDocument = {
  name: string
  system_prompt_append: string
  prompt: string
  context: string
  llm: {
    provider: RunConfigProvider
    model: string
    gateway: 'openrouter'
    reasoning: {
      enabled: boolean
      effort: RunReasoningEffort
    }
    openrouter: {
      base_url: string
      request_timeout_ms: number
      api_key_env: string
    }
  }
  rlm: {
    enabled: boolean
    max_depth: number
  }
  guardrails: {
    max_steps_per_node: number
    max_total_steps_per_run: number
    max_run_duration_ms: number
    max_consecutive_step_failures: number
    max_total_tokens: number
    max_total_cost_usd: string
  }
  accounting: {
    pricing_version: string
    fallback_pricing: Record<
      string,
      Record<
        string,
        {
          input_microusd_per_million_tokens: number
          output_microusd_per_million_tokens: number
        }
      >
    >
  }
}

const EXAMPLE_FALLBACK_PROVIDER: RunConfigProvider = 'openai'
const EXAMPLE_FALLBACK_MODEL = 'gpt-5.3-codex'

function pickRandomWord(words: readonly string[], random: () => number): string {
  return words[Math.floor(random() * words.length)] ?? words[0]
}

export function createAutogeneratedRunName(random: () => number = Math.random): string {
  return [
    pickRandomWord(RUN_NAME_PREFIX_WORDS, random),
    pickRandomWord(RUN_NAME_MIDDLE_WORDS, random),
    pickRandomWord(RUN_NAME_SUFFIX_WORDS, random),
  ].join('-')
}

export function createDefaultRunConfigFormValues(): RunConfigFormValues {
  return {
    name: createAutogeneratedRunName(),
    systemPromptAppend: '',
    prompt: '',
    context: '',
    llm: {
      provider: 'openai',
      model: EXAMPLE_FALLBACK_MODEL,
      reasoning: {
        enabled: false,
        effort: 'medium',
      },
    },
    rlm: {
      enabled: true,
      maxDepth: 3,
    },
  }
}

export function getModelsForProvider(provider: RunConfigProvider): readonly string[] {
  return RUN_PROVIDER_MODELS[provider]
}

export function getDefaultModelForProvider(provider: RunConfigProvider): string {
  return RUN_PROVIDER_MODELS[provider][0]
}

export function resolveModelForProvider(provider: RunConfigProvider, model: string): string {
  const availableModels = RUN_PROVIDER_MODELS[provider]
  return availableModels.some((availableModel) => availableModel === model) ? model : availableModels[0]
}

export function buildRunConfigYaml(formValues: RunConfigFormValues): string {
  const normalizedProvider = formValues.llm.provider
  const normalizedModel = resolveModelForProvider(normalizedProvider, formValues.llm.model)
  const fallbackPricing =
    normalizedProvider === EXAMPLE_FALLBACK_PROVIDER && normalizedModel === EXAMPLE_FALLBACK_MODEL
      ? {
          [EXAMPLE_FALLBACK_PROVIDER]: {
            [EXAMPLE_FALLBACK_MODEL]: {
              input_microusd_per_million_tokens: 1750000,
              output_microusd_per_million_tokens: 14000000,
            },
          },
        }
      : {}

  const document: RunConfigYamlDocument = {
    name: formValues.name,
    system_prompt_append: formValues.systemPromptAppend,
    prompt: formValues.prompt,
    context: formValues.context,
    llm: {
      provider: normalizedProvider,
      model: normalizedModel,
      gateway: 'openrouter',
      reasoning: {
        enabled: formValues.llm.reasoning.enabled,
        effort: formValues.llm.reasoning.effort,
      },
      openrouter: {
        base_url: 'https://openrouter.ai/api/v1',
        request_timeout_ms: 30000,
        api_key_env: 'OPENROUTER_API_KEY',
      },
    },
    rlm: {
      enabled: formValues.rlm.enabled,
      max_depth: Math.max(1, Math.trunc(formValues.rlm.maxDepth || 0)),
    },
    guardrails: {
      max_steps_per_node: 64,
      max_total_steps_per_run: 256,
      max_run_duration_ms: 1200000,
      max_consecutive_step_failures: 6,
      max_total_tokens: 1000000,
      max_total_cost_usd: '5.00',
    },
    accounting: {
      pricing_version: 'openrouter-2026-03-07',
      fallback_pricing: fallbackPricing,
    },
  }

  return stringify(document, {
    lineWidth: 0,
  })
}

export function parseRunConfigMetadataFromYaml(runConfigYaml: string): ParsedRunConfigMetadata | null {
  try {
    const parsed = parse(runConfigYaml)
    if (parsed == null || typeof parsed !== 'object' || Array.isArray(parsed)) {
      return null
    }

    const name = (parsed as Record<string, unknown>).name
    const rlm = (parsed as Record<string, unknown>).rlm
    const maxDepthValue =
      rlm != null && typeof rlm === 'object' && !Array.isArray(rlm) ? (rlm as Record<string, unknown>).max_depth : null

    if (typeof name !== 'string' || name.trim().length === 0) {
      return null
    }

    return {
      name: name.trim(),
      maxDepth:
        typeof maxDepthValue === 'number' && Number.isFinite(maxDepthValue) && maxDepthValue > 0 ? maxDepthValue : 1,
    }
  } catch {
    return null
  }
}
