import { describe, expect, it } from 'vitest'
import {
  buildRunConfigYaml,
  createAutogeneratedRunName,
  createDefaultRunConfigFormValues,
  parseRunConfigMetadataFromYaml,
  resolveModelForProvider,
} from './run-config'

describe('run config helpers', () => {
  it('creates autogenerated run names as three hyphen-delimited words', () => {
    expect(createAutogeneratedRunName(() => 0)).toBe('amber-anchor-atlas')
    expect(createDefaultRunConfigFormValues().name).toMatch(/^[a-z]+-[a-z]+-[a-z]+$/)
  })

  it('defaults optional long-form fields to empty strings so placeholders can render', () => {
    expect(createDefaultRunConfigFormValues()).toMatchObject({
      context: '',
      systemPromptAppend: '',
    })
  })

  it('serializes prompt and context fields with example-backed hidden settings', () => {
    const yaml = buildRunConfigYaml({
      ...createDefaultRunConfigFormValues(),
      name: 'workspace-run',
      prompt: 'Summarize the latest run output.',
      context: 'Context line one.\nContext line two.',
    })

    expect(yaml).toContain('name: workspace-run')
    expect(yaml).toContain('prompt: Summarize the latest run output.')
    expect(yaml).toContain('context: |')
    expect(yaml).toContain('gateway: openrouter')
    expect(yaml).toContain('pricing_version: openrouter-2026-03-07')
    expect(yaml).not.toContain('prompt_template')
    expect(yaml).not.toContain('context_template')
  })

  it('drops example fallback pricing when provider and model change away from the example pair', () => {
    const yaml = buildRunConfigYaml({
      ...createDefaultRunConfigFormValues(),
      prompt: 'Answer the operator prompt.',
      llm: {
        provider: 'anthropic',
        model: 'claude-sonnet-4',
        reasoning: {
          enabled: true,
          effort: 'high',
        },
      },
    })

    expect(yaml).toContain('fallback_pricing: {}')
    expect(yaml).toContain('provider: anthropic')
    expect(yaml).toContain('model: claude-sonnet-4')
  })

  it('keeps provider models aligned when a mismatched model is selected', () => {
    expect(resolveModelForProvider('anthropic', 'gpt-5.3-codex')).toBe('claude-sonnet-4')
    expect(resolveModelForProvider('openai', 'gpt-5.3-codex')).toBe('gpt-5.3-codex')
  })

  it('parses run metadata from yaml', () => {
    expect(
      parseRunConfigMetadataFromYaml('name: live-run\nprompt: hello\ncontext: world\nrlm:\n  max_depth: 4\n'),
    ).toEqual({
      name: 'live-run',
      maxDepth: 4,
    })
  })
})
