import { defineConfig } from 'vite-plus'
import { devtools } from '@tanstack/devtools-vite'
import { tanstackStart } from '@tanstack/react-start/plugin/vite'
import viteReact from '@vitejs/plugin-react'
import tailwindcss from '@tailwindcss/vite'

const config = defineConfig({
  staged: {
    '*': 'vp check --fix',
  },
  fmt: {
    semi: false,
    singleQuote: true,
    trailingComma: 'all',
    printWidth: 100,
    sortPackageJson: false,
    ignorePatterns: ['package-lock.json', 'pnpm-lock.yaml', 'yarn.lock'],
  },
  lint: {
    plugins: ['import', 'typescript'],
    categories: {
      correctness: 'off',
    },
    env: {
      builtin: true,
    },
    ignorePatterns: [
      '**/.nx/**',
      '**/.svelte-kit/**',
      '**/build/**',
      '**/coverage/**',
      '**/dist/**',
      '**/snap/**',
      '**/vite.config.*.timestamp-*.*',
    ],
    rules: {},
    overrides: [
      {
        files: ['**/*.{js,ts,tsx}'],
        rules: {
          'for-direction': 'error',
          'no-async-promise-executor': 'error',
          'no-case-declarations': 'error',
          'no-class-assign': 'error',
          'no-compare-neg-zero': 'error',
          'no-cond-assign': 'error',
          'no-constant-binary-expression': 'error',
          'no-constant-condition': 'error',
          'no-control-regex': 'error',
          'no-debugger': 'error',
          'no-delete-var': 'error',
          'no-dupe-else-if': 'error',
          'no-duplicate-case': 'error',
          'no-empty-character-class': 'error',
          'no-empty-pattern': 'error',
          'no-empty-static-block': 'error',
          'no-ex-assign': 'error',
          'no-extra-boolean-cast': 'error',
          'no-fallthrough': 'error',
          'no-global-assign': 'error',
          'no-invalid-regexp': 'error',
          'no-irregular-whitespace': 'error',
          'no-loss-of-precision': 'error',
          'no-misleading-character-class': 'error',
          'no-nonoctal-decimal-escape': 'error',
          'no-regex-spaces': 'error',
          'no-self-assign': 'error',
          'no-shadow': 'warn',
          'no-shadow-restricted-names': 'error',
          'no-sparse-arrays': 'error',
          'no-unsafe-finally': 'error',
          'no-unsafe-optional-chaining': 'error',
          'no-unused-labels': 'error',
          'no-unused-private-class-members': 'error',
          'no-useless-backreference': 'error',
          'no-useless-catch': 'error',
          'no-useless-escape': 'error',
          'no-var': 'error',
          'no-with': 'error',
          'prefer-const': 'error',
          'require-yield': 'error',
          'use-isnan': 'error',
          'valid-typeof': 'error',
          '@typescript-eslint/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': false,
              'ts-ignore': 'allow-with-description',
            },
          ],
          '@typescript-eslint/consistent-type-imports': [
            'error',
            {
              prefer: 'type-imports',
            },
          ],
          '@typescript-eslint/no-duplicate-enum-values': 'error',
          '@typescript-eslint/no-extra-non-null-assertion': 'error',
          '@typescript-eslint/no-inferrable-types': [
            'error',
            {
              ignoreParameters: true,
            },
          ],
          '@typescript-eslint/no-misused-new': 'error',
          '@typescript-eslint/no-namespace': 'error',
          '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
          '@typescript-eslint/no-unsafe-function-type': 'error',
          '@typescript-eslint/no-wrapper-object-types': 'error',
          '@typescript-eslint/prefer-as-const': 'error',
          '@typescript-eslint/prefer-for-of': 'warn',
          '@typescript-eslint/triple-slash-reference': 'error',
          'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
          'import/first': 'error',
          'import/no-commonjs': 'error',
          'import/no-duplicates': 'error',
        },
        env: {
          es2020: true,
          browser: true,
        },
      },
      {
        files: ['**/*.vue'],
        rules: {
          'for-direction': 'error',
          'no-async-promise-executor': 'error',
          'no-case-declarations': 'error',
          'no-class-assign': 'error',
          'no-compare-neg-zero': 'error',
          'no-cond-assign': 'error',
          'no-constant-binary-expression': 'error',
          'no-constant-condition': 'error',
          'no-control-regex': 'error',
          'no-debugger': 'error',
          'no-delete-var': 'error',
          'no-dupe-else-if': 'error',
          'no-duplicate-case': 'error',
          'no-empty-character-class': 'error',
          'no-empty-pattern': 'error',
          'no-empty-static-block': 'error',
          'no-ex-assign': 'error',
          'no-extra-boolean-cast': 'error',
          'no-fallthrough': 'error',
          'no-global-assign': 'error',
          'no-invalid-regexp': 'error',
          'no-irregular-whitespace': 'error',
          'no-loss-of-precision': 'error',
          'no-misleading-character-class': 'error',
          'no-nonoctal-decimal-escape': 'error',
          'no-regex-spaces': 'error',
          'no-self-assign': 'error',
          'no-shadow': 'warn',
          'no-shadow-restricted-names': 'error',
          'no-sparse-arrays': 'error',
          'no-unsafe-finally': 'error',
          'no-unsafe-optional-chaining': 'error',
          'no-unused-labels': 'error',
          'no-unused-private-class-members': 'error',
          'no-useless-backreference': 'error',
          'no-useless-catch': 'error',
          'no-useless-escape': 'error',
          'no-var': 'error',
          'no-with': 'error',
          'prefer-const': 'error',
          'require-yield': 'error',
          'use-isnan': 'error',
          'valid-typeof': 'error',
          '@typescript-eslint/ban-ts-comment': [
            'error',
            {
              'ts-expect-error': false,
              'ts-ignore': 'allow-with-description',
            },
          ],
          '@typescript-eslint/consistent-type-imports': [
            'error',
            {
              prefer: 'type-imports',
            },
          ],
          '@typescript-eslint/no-duplicate-enum-values': 'error',
          '@typescript-eslint/no-extra-non-null-assertion': 'error',
          '@typescript-eslint/no-inferrable-types': [
            'error',
            {
              ignoreParameters: true,
            },
          ],
          '@typescript-eslint/no-misused-new': 'error',
          '@typescript-eslint/no-namespace': 'error',
          '@typescript-eslint/no-non-null-asserted-optional-chain': 'error',
          '@typescript-eslint/no-unsafe-function-type': 'error',
          '@typescript-eslint/no-wrapper-object-types': 'error',
          '@typescript-eslint/prefer-as-const': 'error',
          '@typescript-eslint/prefer-for-of': 'warn',
          '@typescript-eslint/triple-slash-reference': 'error',
          'import/consistent-type-specifier-style': ['error', 'prefer-top-level'],
          'import/first': 'error',
          'import/no-commonjs': 'error',
          'import/no-duplicates': 'error',
        },
        env: {
          browser: true,
        },
      },
    ],
    options: {
      typeAware: true,
      typeCheck: true,
    },
  },
  resolve: {
    tsconfigPaths: true,
  },
  plugins: [devtools(), tailwindcss(), tanstackStart(), viteReact()],
})

export default config
