import assert from 'node:assert/strict'
import { Then, When } from '@cucumber/cucumber'
import { waitForCondition, waitForSelectorText, waitForUrlSuffix } from '../support/assertions'
import type { SigilWebWorld } from '../support/world'

async function hasAttribute(world: SigilWebWorld, selector: string, attributeName: string): Promise<boolean> {
  try {
    const value = await world.browser.getAttr(selector, attributeName)
    return value !== 'null' && value !== 'undefined'
  } catch {
    return false
  }
}

Then('the selected agent name is {string}', async function (this: SigilWebWorld, expectedName: string) {
  await waitForSelectorText(this.browser, '[data-testid="selected-agent-name"]', expectedName)
})

Then('the hidden agent search value is {string}', async function (this: SigilWebWorld, expectedValue: string) {
  await waitForCondition(
    async () => (await this.browser.getValue('[data-testid="agent-search-param"]')) === expectedValue,
    `Timed out waiting for hidden agent search value ${expectedValue}`,
  )
})

When('the user selects agent card {string}', async function (this: SigilWebWorld, agentId: string) {
  await this.browser.waitForSelector(`[data-testid="sidebar-agent-${agentId}"]`)
  await this.browser.click(`[data-testid="sidebar-agent-${agentId}"]`)
})

When('the user filters the fleet by {string}', async function (this: SigilWebWorld, filterText: string) {
  await this.browser.fill('[data-testid="fleet-filter"]', filterText)
})

Then('the visible fleet card count is {int}', async function (this: SigilWebWorld, expectedCount: number) {
  await waitForCondition(
    async () => (await this.browser.getCount('[data-testid^="sidebar-agent-"]')) === expectedCount,
    `Timed out waiting for ${expectedCount} visible fleet cards`,
  )
})

Then('the fleet badge count is {int}', async function (this: SigilWebWorld, expectedCount: number) {
  assert.equal(Number.parseInt(await this.browser.getText('[data-testid="fleet-count"]'), 10), expectedCount)
})

When('the user opens the new run dialog', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-button"]')
})

Then('the new run dialog is visible', async function (this: SigilWebWorld) {
  await this.browser.waitForSelector('[data-testid="new-run-dialog"]')
})

When('the user opens the new run form tab', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-tab-form"]')
  await this.browser.waitForSelector('[data-testid="new-run-textarea-prompt"]')
})

When('the user opens the new run YAML tab', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-tab-yaml"]')
  await this.browser.waitForSelector('[data-testid="new-run-textarea-yaml"]')
})

When('the user enters {string} into the new run name field', async function (this: SigilWebWorld, value: string) {
  await this.browser.click('[data-testid="new-run-customize-name-button"]')
  await this.browser.fill('[data-testid="new-run-input-name"]', value)
})

When('the user enters {string} into the new run prompt field', async function (this: SigilWebWorld, value: string) {
  await this.browser.fill('[data-testid="new-run-textarea-prompt"]', value)
})

When('the user restores autogenerated mode for the new run name', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-use-autogenerated-name-button"]')
})

When('the user enables custom editing for the new run name', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-customize-name-button"]')
})

When('the user enables reasoning for the new run', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-checkbox-reasoning-enabled"]')
})

When('the user disables RLM for the new run', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-checkbox-rlm-enabled"]')
})

When('the user replaces the new run YAML with:', async function (this: SigilWebWorld, yamlText: string) {
  await this.browser.fill('[data-testid="new-run-textarea-yaml"]', yamlText)
})

When('the user resets the new run YAML from the form', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-reset-yaml-button"]')
})

When('the user submits the new run dialog', async function (this: SigilWebWorld) {
  await this.browser.click('[data-testid="new-run-submit-button"]')
})

Then('the new run YAML contains {string}', async function (this: SigilWebWorld, expectedText: string) {
  await waitForCondition(
    async () => (await this.browser.getValue('[data-testid="new-run-textarea-yaml"]')).includes(expectedText),
    `Timed out waiting for the new run YAML to contain ${expectedText}`,
  )
})

Then('the new run YAML does not contain {string}', async function (this: SigilWebWorld, unexpectedText: string) {
  await waitForCondition(
    async () => !(await this.browser.getValue('[data-testid="new-run-textarea-yaml"]')).includes(unexpectedText),
    `Timed out waiting for the new run YAML to omit ${unexpectedText}`,
  )
})

Then('the new run inline error says {string}', async function (this: SigilWebWorld, message: string) {
  await waitForSelectorText(this.browser, '[data-testid="new-run-inline-error"]', message)
})

Then('the autogenerated new run name matches a three-word slug', async function (this: SigilWebWorld) {
  const runName = await this.browser.getValue('[data-testid="new-run-input-name"]')
  assert.match(runName, /^[a-z]+-[a-z]+-[a-z]+$/)
})

Then('the current new run name is remembered', async function (this: SigilWebWorld) {
  this.rememberedRunName = await this.browser.getValue('[data-testid="new-run-input-name"]')
  assert.ok(this.rememberedRunName)
})

Then('the current new run name matches the remembered value', async function (this: SigilWebWorld) {
  assert.ok(this.rememberedRunName, 'expected a remembered run name')
  assert.equal(await this.browser.getValue('[data-testid="new-run-input-name"]'), this.rememberedRunName)
})

Then('the autogenerated new run name differs from the remembered value', async function (this: SigilWebWorld) {
  assert.ok(this.rememberedRunName, 'expected a remembered run name')
  assert.notEqual(await this.browser.getValue('[data-testid="new-run-input-name"]'), this.rememberedRunName)
})

Then('the new run name input is read only', async function (this: SigilWebWorld) {
  await waitForCondition(
    async () => hasAttribute(this, '[data-testid="new-run-input-name"]', 'readonly'),
    'Timed out waiting for the new run name input to become read only',
  )
})

Then('the new run name input is enabled', async function (this: SigilWebWorld) {
  const currentValue = await this.browser.getValue('[data-testid="new-run-input-name"]')
  const nextValue = `${currentValue}-custom`
  await this.browser.fill('[data-testid="new-run-input-name"]', nextValue)
  await waitForCondition(
    async () => (await this.browser.getValue('[data-testid="new-run-input-name"]')) === nextValue,
    'Timed out waiting for the new run name input to accept edits',
  )
})

Then('the new run reasoning effort control is disabled', async function (this: SigilWebWorld) {
  await waitForCondition(
    async () => hasAttribute(this, '[data-testid="new-run-select-reasoning-effort"]', 'disabled'),
    'Timed out waiting for reasoning effort to become disabled',
  )
})

Then('the new run reasoning effort control is enabled', async function (this: SigilWebWorld) {
  await this.browser.select('[data-testid="new-run-select-reasoning-effort"]', 'high')
  await waitForCondition(
    async () => (await this.browser.getValue('[data-testid="new-run-select-reasoning-effort"]')) === 'high',
    'Timed out waiting for reasoning effort to accept selection changes',
  )
})

Then('the new run RLM depth control is disabled', async function (this: SigilWebWorld) {
  await waitForCondition(
    async () => hasAttribute(this, '[data-testid="new-run-input-rlm-max-depth"]', 'disabled'),
    'Timed out waiting for RLM depth to become disabled',
  )
})

Then('the new run RLM depth control is enabled', async function (this: SigilWebWorld) {
  await this.browser.fill('[data-testid="new-run-input-rlm-max-depth"]', '4')
  await waitForCondition(
    async () => (await this.browser.getValue('[data-testid="new-run-input-rlm-max-depth"]')) === '4',
    'Timed out waiting for RLM depth to accept edits',
  )
})

When('the user connects the demo endpoint {string}', async function (this: SigilWebWorld, endpoint: string) {
  await this.browser.fill('[data-testid="connect-agent-endpoint"]', endpoint)
  await waitForCondition(
    async () => (await this.browser.getValue('[data-testid="connect-agent-endpoint"]')) === endpoint,
    `Timed out waiting for the demo endpoint input ${endpoint}`,
  )
  await this.browser.click('[data-testid="connect-agent-button"]')
})

When('the user selects the agent card named {string}', async function (this: SigilWebWorld, agentName: string) {
  await this.browser.fill('[data-testid="fleet-filter"]', agentName)
  await waitForCondition(
    async () => (await this.browser.getCount('[data-testid^="sidebar-agent-"]')) === 1,
    `Timed out waiting for a single visible fleet card matching ${agentName}`,
  )
  await this.browser.click('[data-testid^="sidebar-agent-"]')
})

Then('the runs empty state is visible', async function (this: SigilWebWorld) {
  await this.browser.waitForSelector('[data-testid="runs-empty-state"]')
  await waitForSelectorText(this.browser, '[data-testid="runs-empty-state"]', 'No runs for this agent.')
})

Then('the root run-detail empty prompt is visible', async function (this: SigilWebWorld) {
  await this.browser.waitForSelector('[data-testid="run-detail-empty-state"]')
  await waitForSelectorText(this.browser, '[data-testid="run-detail-empty-state"]', 'Select a run to view details.')
})

Then('the root run detail tabs are visible', async function (this: SigilWebWorld) {
  await this.browser.waitForSelector('[data-testid="run-detail-tabs"]')
  const tabText = await this.browser.getText('[data-testid="run-detail-tabs"]')
  for (const label of ['Timeline', 'Nodes', 'Steps', 'Meta']) {
    assert.match(tabText, new RegExp(label))
  }
})

When('the user selects run {string}', async function (this: SigilWebWorld, runId: string) {
  await this.browser.click(`[data-testid="run-item-${runId}"]`)
})

When('the user opens the selected run detail route', async function (this: SigilWebWorld) {
  await this.browser.waitForSelector('[data-testid="open-run-detail"]')
  await this.browser.click('[data-testid="open-run-detail"]')
})

Then('the browser URL ends with {string}', async function (this: SigilWebWorld, expectedSuffix: string) {
  await waitForUrlSuffix(this.browser, expectedSuffix)
})

Then(
  'the selected agent workspace shows run {string} as {string}',
  async function (this: SigilWebWorld, runId: string, expectedState: string) {
    const normalizedState = expectedState.toLowerCase()
    const label = normalizedState.charAt(0).toUpperCase() + normalizedState.slice(1)
    await waitForSelectorText(this.browser, `[data-testid="run-item-${runId}"]`, label)
    if (normalizedState === 'completed') {
      await this.browser.click('[data-testid="run-detail-tab-meta"]')
      await waitForSelectorText(this.browser, '[data-testid="run-detail-meta-panel"]', normalizedState)
    }
  },
)
