Feature: Sigil-web root workspace contracts
  The root workspace keeps agent selection, run detail, and fleet visibility
  behavior stable for the current product surface.

  Scenario: Defaults the root workspace selection to the first available agent and reflects its canonical Agent Instance ID in the agent search param
    Given the demo workspace is open
    Then the selected agent name is "needle-search"
    And the hidden agent search value is "needle-search"

  Scenario: Resolves exact canonical Agent Instance IDs and falls back when the agent search value is invalid or legacy
    Given the demo workspace is open at "/?agent=needle-search"
    Then the selected agent name is "needle-search"
    Given the demo workspace is open at "/?agent=agent_mrcr_2needle"
    Then the selected agent name is "needle-search"

  Scenario: Updates root workspace selection when a different agent card is chosen
    Given the demo workspace is open
    When the user selects agent card "mrcr-2needle"
    Then the selected agent name is "mrcr-2needle"
    And the hidden agent search value is "mrcr-2needle"

  Scenario: Filters agent cards by instance name or endpoint without mutating the underlying fleet
    Given the demo workspace is open
    When the user filters the fleet by "mrcr-4needle"
    Then the visible fleet card count is 1
    And the fleet badge count is 3

  Scenario: Opens the selected-agent new-run dialog as a centered modal from the root workspace
    Given the demo workspace is open
    When the user opens the new run dialog
    Then the new run dialog is visible

  Scenario: Regenerates run YAML from form edits while the dialog remains in generated mode
    Given the demo workspace is open
    When the user opens the new run dialog
    And the user enters "workspace-run" into the new run name field
    And the user enters "Summarize the latest run output." into the new run prompt field
    And the user opens the new run YAML tab
    Then the new run YAML contains "name: workspace-run"
    And the new run YAML contains "prompt: Summarize the latest run output."

  Scenario: Preserves manual YAML edits without back-populating from later form changes
    Given the demo workspace is open
    When the user opens the new run dialog
    And the user enters "Form prompt before manual yaml." into the new run prompt field
    And the user opens the new run YAML tab
    And the user replaces the new run YAML with:
      """
      name: manual-yaml-run
      prompt: Manual YAML prompt.
      context: Manual YAML context.
      llm:
        provider: openai
        model: gpt-5.3-codex
        gateway: openrouter
        reasoning:
          enabled: false
          effort: medium
        openrouter:
          base_url: https://openrouter.ai/api/v1
          request_timeout_ms: 30000
          api_key_env: OPENROUTER_API_KEY
      rlm:
        enabled: true
        max_depth: 3
      guardrails:
        max_steps_per_node: 64
        max_total_steps_per_run: 256
        max_run_duration_ms: 1200000
        max_consecutive_step_failures: 6
        max_total_tokens: 1000000
        max_total_cost_usd: "5.00"
      accounting:
        pricing_version: openrouter-2026-03-07
        fallback_pricing:
          openai:
            gpt-5.3-codex:
              input_microusd_per_million_tokens: 1750000
              output_microusd_per_million_tokens: 14000000
      """
    And the user opens the new run form tab
    And the user enters "Updated form prompt that should not overwrite yaml." into the new run prompt field
    And the user opens the new run YAML tab
    Then the new run YAML contains "name: manual-yaml-run"
    And the new run YAML contains "prompt: Manual YAML prompt."
    And the new run YAML does not contain "Updated form prompt that should not overwrite yaml."

  Scenario: Restores generated YAML when the operator resets the manual YAML draft
    Given the demo workspace is open
    When the user opens the new run dialog
    And the user enters "Prompt restored from form." into the new run prompt field
    And the user opens the new run YAML tab
    And the user replaces the new run YAML with:
      """
      name: manual-yaml-run
      prompt: Manual YAML prompt.
      context: Manual YAML context.
      """
    And the user resets the new run YAML from the form
    Then the new run YAML contains "prompt: Prompt restored from form."
    And the new run YAML does not contain "prompt: Manual YAML prompt."

  Scenario: Defaults the run name to a read-only autogenerated slug and allows customizing or restoring it
    Given the demo workspace is open
    When the user opens the new run dialog
    Then the autogenerated new run name matches a three-word slug
    And the current new run name is remembered
    And the new run name input is read only
    When the user enables custom editing for the new run name
    Then the current new run name matches the remembered value
    And the new run name input is enabled
    When the user restores autogenerated mode for the new run name
    Then the autogenerated new run name matches a three-word slug
    And the autogenerated new run name differs from the remembered value
    And the new run name input is read only

  Scenario: Enables reasoning effort and RLM depth only when their parent toggles are enabled
    Given the demo workspace is open
    When the user opens the new run dialog
    Then the new run reasoning effort control is disabled
    And the new run RLM depth control is enabled
    When the user enables reasoning for the new run
    Then the new run reasoning effort control is enabled
    When the user disables RLM for the new run
    Then the new run RLM depth control is disabled

  Scenario: Loads the selected run detail in the root workspace when the selected agent has runs
    Given the demo workspace is open
    When the user selects agent card "needle-search"
    Then the root run detail tabs are visible
    And the selected agent workspace shows run "019d1767-410f-7659-8f98-5657c78271de" as "completed"

  Scenario: Shows an empty run-detail prompt when the selected agent has no runs
    Given the demo workspace is open
    When the user connects the demo endpoint "ws://empty-agent.local:8765/app-server"
    And the user selects the agent card named "empty-agent.local"
    Then the runs empty state is visible
    And the root run-detail empty prompt is visible

  Scenario: Opens the selected run in the standalone run-detail route from the root workspace
    Given the demo workspace is open
    When the user selects run "019d1767-410f-7659-8f98-5657c78271de"
    And the user opens the selected run detail route
    Then the browser URL ends with "/runs/019d1767-410f-7659-8f98-5657c78271de"
