// Code generated by sigil app-server generate-ts. DO NOT EDIT.
export const PROTOCOL_VERSION = "sigil.appserver.v1alpha1" as const;
export const SUPPORTED_PROTOCOL_VERSIONS = ["sigil.appserver.v1alpha1"] as const;

export interface ArtifactIdentityView {
  nodeId?: string;
  stepId?: string;
  actionIndex?: number;
  subcallIndex?: number;
}

export interface ClientInfo {
  name: string;
  version?: string;
}

export interface ConfigCapability {
  defaultVersion: string;
  supportedVersions: string[];
}

export interface ErrorData {
  code: string;
  retryable?: boolean;
  details?: Record<string, unknown>;
}

export interface ErrorObject {
  code: number;
  message: string;
  data?: ErrorData;
}

export interface EventEnvelopeView {
  eventId: string;
  schemaVersion: string;
  runId: string;
  seq: number;
  ts: string;
  type: string;
  nodeId?: string;
  causationId: string;
  correlationId: string;
  payload: Record<string, unknown>;
}

export interface InitializeParams {
  protocolVersions: string[];
  client: ClientInfo;
}

export interface InitializeResult {
  serverName: string;
  serverVersion: string;
  instanceId: string;
  instanceName: string;
  protocolVersion: string;
  methodFamilies: string[];
  capabilities: ServerCapabilities;
}

export interface InitializedParams {
}

export interface ProcessMetadataView {
  runId: string;
  pid: number;
  recordedAt: string;
  startedAt: string;
  source: string;
}

export interface RunArtifactReadParams {
  runId: string;
  artifactRef: string;
}

export interface RunArtifactReadPayload {
  artifactRef: string;
  artifactKind: string;
  identity: ArtifactIdentityView;
  artifact: Record<string, unknown>;
}

export interface RunArtifactReadResult {
  runId: string;
  payload: RunArtifactReadPayload;
}

export interface RunCompletedParams {
  runId: string;
  seq: number;
  payload: RunCompletedPayload;
}

export interface RunCompletedPayload {
  state: string;
  terminal: boolean;
}

export interface RunEventAppendedParams {
  runId: string;
  seq: number;
  payload: RunEventAppendedPayload;
}

export interface RunEventAppendedPayload {
  event: EventEnvelopeView;
}

export interface RunEventsReadParams {
  runId: string;
}

export interface RunEventsReadPayload {
  firstSeq?: number;
  lastSeq?: number;
  events: EventEnvelopeView[];
}

export interface RunEventsReadResult {
  runId: string;
  payload: RunEventsReadPayload;
}

export interface RunListParams {
  limit?: number;
  cursor?: string;
}

export interface RunListPayload {
  items: RunSummaryView[];
  nextCursor?: string;
}

export interface RunListResult {
  payload: RunListPayload;
}

export interface RunNodeDetailView {
  nodeId: string;
  parentNodeId?: string;
  depth: number;
  role?: string;
  state: string;
  startedAt?: string;
  terminalAt?: string;
  stepCount: number;
  resultRef?: string;
  accountingRef?: string;
  errorCode?: string;
  errorMessage?: string;
  stepIds?: string[];
  activeStepId?: string;
  childNodeIds?: string[];
}

export interface RunNodeProjectionView {
  nodeId: string;
  parentNodeId?: string;
  depth: number;
  role?: string;
  state: string;
  startedAt?: string;
  terminalAt?: string;
  stepCount: number;
  resultRef?: string;
  accountingRef?: string;
  errorCode?: string;
  errorMessage?: string;
}

export interface RunNodeReadParams {
  runId: string;
  nodeId: string;
}

export interface RunNodeReadPayload {
  node: RunNodeDetailView;
}

export interface RunNodeReadResult {
  runId: string;
  asOfSeq: number;
  payload: RunNodeReadPayload;
}

export interface RunProjectionView {
  runId: string;
  state: string;
  runDir: string;
  eventsPath: string;
  source?: string;
  appConfigPath?: string;
  runConfigPath?: string;
  queuedAt?: string;
  startedAt?: string;
  terminalAt?: string;
  executor?: string;
  maxDepth: number;
  pidStatus: string;
  stopRequested: boolean;
  processMetadata?: ProcessMetadataView;
  stopRequest?: StopRequestMetadataView;
  finalAnswerRef?: string;
  accountingRef?: string;
  errorCode?: string;
  errorMessage?: string;
  failedNodeId?: string;
  failedStepId?: string;
  interruptedReason?: string;
  interruptedBy?: string;
  interruptedNodeId?: string;
  nodeCount: number;
  stepCount: number;
  actionCount: number;
  subcallCount: number;
  nodes: RunNodeProjectionView[];
}

export interface RunReadParams {
  runId: string;
}

export interface RunReadPayload {
  run: RunProjectionView;
}

export interface RunReadResult {
  runId: string;
  asOfSeq: number;
  payload: RunReadPayload;
}

export interface RunStartParams {
  runConfigYaml: string;
  templateVars?: Record<string, string>;
}

export interface RunStartPayload {
  run: RunProjectionView;
}

export interface RunStartResult {
  runId: string;
  asOfSeq: number;
  payload: RunStartPayload;
}

export interface RunStartedParams {
  runId: string;
  seq: number;
  payload: RunStartedPayload;
}

export interface RunStartedPayload {
  run: RunProjectionView;
}

export interface RunStatusChangedParams {
  runId: string;
  seq: number;
  payload: RunStatusChangedPayload;
}

export interface RunStatusChangedPayload {
  state: string;
  terminal: boolean;
}

export interface RunStepDetailView {
  nodeId: string;
  stepId: string;
  nodeStepIndex: number;
  stepStartedSeq: number;
  schemaId: string;
  decision?: string;
  state: string;
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
  actionCount: number;
  subcallCount: number;
  userTurnRef?: string;
  modelTurnRef?: string;
  accountingRef?: string;
  errorCode?: string;
  errorMessage?: string;
  actionRefs?: string[];
  subcallAccountingRefs?: string[];
}

export interface RunStepReadParams {
  runId: string;
  nodeId: string;
  stepId: string;
}

export interface RunStepReadPayload {
  step: RunStepDetailView;
}

export interface RunStepReadResult {
  runId: string;
  asOfSeq: number;
  payload: RunStepReadPayload;
}

export interface RunStepSummaryView {
  nodeId: string;
  stepId: string;
  nodeStepIndex: number;
  stepStartedSeq: number;
  schemaId: string;
  decision?: string;
  state: string;
  startedAt?: string;
  completedAt?: string;
  durationMs?: number;
  actionCount: number;
  subcallCount: number;
  userTurnRef?: string;
  modelTurnRef?: string;
  accountingRef?: string;
  errorCode?: string;
  errorMessage?: string;
}

export interface RunStepsListParams {
  runId: string;
}

export interface RunStepsListPayload {
  steps: RunStepSummaryView[];
}

export interface RunStepsListResult {
  runId: string;
  asOfSeq: number;
  payload: RunStepsListPayload;
}

export interface RunStopParams {
  runId: string;
}

export interface RunStopPayload {
  stopRequested: boolean;
  state: string;
  eventsPath: string;
}

export interface RunStopResult {
  runId: string;
  payload: RunStopPayload;
}

export interface RunSubscribeParams {
  runId: string;
  afterSeq?: number;
}

export interface RunSubscribePayload {
  snapshot?: RunSubscriptionSnapshotView;
  replayEvents?: EventEnvelopeView[];
  terminal: boolean;
}

export interface RunSubscribeResult {
  runId: string;
  snapshotAsOfSeq: number;
  payload: RunSubscribePayload;
}

export interface RunSubscriptionSnapshotView {
  run: RunProjectionView;
  tree: RunTreeReadPayload;
  activeNodeId?: string;
  activeStepId?: string;
  terminal: boolean;
}

export interface RunSummaryView {
  runId: string;
  state: string;
  source?: string;
  queuedAt?: string;
  startedAt?: string;
  terminalAt?: string;
  eventsPath: string;
  pidStatus: string;
  stopRequested: boolean;
  finalAnswerRef?: string;
  accountingRef?: string;
  error?: string;
}

export interface RunTreeNodeView {
  nodeId: string;
  parentNodeId?: string;
  depth: number;
  role?: string;
  state: string;
  startedAt?: string;
  terminalAt?: string;
  stepCount: number;
  resultRef?: string;
  accountingRef?: string;
  errorCode?: string;
  errorMessage?: string;
  childNodeIds?: string[];
}

export interface RunTreeReadParams {
  runId: string;
}

export interface RunTreeReadPayload {
  rootNodeId?: string;
  nodes: RunTreeNodeView[];
}

export interface RunTreeReadResult {
  runId: string;
  asOfSeq: number;
  payload: RunTreeReadPayload;
}

export interface RunUnsubscribeParams {
  runId: string;
}

export interface RunUnsubscribePayload {
  unsubscribed: boolean;
}

export interface RunUnsubscribeResult {
  runId: string;
  payload: RunUnsubscribePayload;
}

export interface ServerCapabilities {
  config: ConfigCapability;
  views: ViewCapabilities;
  protocolArtifacts: boolean;
}

export interface ServerHeartbeatParams {
  instanceId: string;
  serverTime: string;
  heartbeatIntervalMs: number;
}

export interface ServerPingParams {
}

export interface ServerPingResult {
  serverName: string;
  serverVersion: string;
  instanceId: string;
  protocolVersion: string;
  serverTime: string;
}

export interface StopRequestMetadataView {
  runId: string;
  requestedAt: string;
  requestedBy: string;
  signal: string;
}

export interface ViewCapabilities {
  runTree: boolean;
  stepDetail: boolean;
  liveSubscriptions: boolean;
}

export interface AppServerMethodMap {
  "initialize": {
    kind: "request";
    params: InitializeParams;
    result: InitializeResult;
  };
  "initialized": {
    kind: "notification";
    params: InitializedParams;
  };
  "run/artifact/read": {
    kind: "request";
    params: RunArtifactReadParams;
    result: RunArtifactReadResult;
  };
  "run/completed": {
    kind: "notification";
    params: RunCompletedParams;
  };
  "run/eventAppended": {
    kind: "notification";
    params: RunEventAppendedParams;
  };
  "run/events/read": {
    kind: "request";
    params: RunEventsReadParams;
    result: RunEventsReadResult;
  };
  "run/list": {
    kind: "request";
    params: RunListParams;
    result: RunListResult;
  };
  "run/node/read": {
    kind: "request";
    params: RunNodeReadParams;
    result: RunNodeReadResult;
  };
  "run/read": {
    kind: "request";
    params: RunReadParams;
    result: RunReadResult;
  };
  "run/start": {
    kind: "request";
    params: RunStartParams;
    result: RunStartResult;
  };
  "run/started": {
    kind: "notification";
    params: RunStartedParams;
  };
  "run/statusChanged": {
    kind: "notification";
    params: RunStatusChangedParams;
  };
  "run/step/read": {
    kind: "request";
    params: RunStepReadParams;
    result: RunStepReadResult;
  };
  "run/steps/list": {
    kind: "request";
    params: RunStepsListParams;
    result: RunStepsListResult;
  };
  "run/stop": {
    kind: "request";
    params: RunStopParams;
    result: RunStopResult;
  };
  "run/subscribe": {
    kind: "request";
    params: RunSubscribeParams;
    result: RunSubscribeResult;
  };
  "run/tree/read": {
    kind: "request";
    params: RunTreeReadParams;
    result: RunTreeReadResult;
  };
  "run/unsubscribe": {
    kind: "request";
    params: RunUnsubscribeParams;
    result: RunUnsubscribeResult;
  };
  "server/heartbeat": {
    kind: "notification";
    params: ServerHeartbeatParams;
  };
  "server/ping": {
    kind: "request";
    params: ServerPingParams;
    result: ServerPingResult;
  };
}
