import { useEffect, useReducer, useState } from 'react'
import type { ChangeEvent, FormEvent, ReactNode } from 'react'
import { ChevronDown, LoaderCircle, RotateCcw } from 'lucide-react'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '#/components/ui/dialog'
import { Input } from '#/components/ui/input'
import { ScrollArea } from '#/components/ui/scroll-area'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '#/components/ui/tabs'
import { Textarea } from '#/components/ui/textarea'
import type { AgentInstance } from '#/lib/demo-data'
import { AppServerRequestError } from '#/lib/appserver/client'
import {
  RUN_PROVIDERS,
  RUN_REASONING_EFFORTS,
  createAutogeneratedRunName,
  getModelsForProvider,
  resolveModelForProvider,
} from '#/lib/run-config'
import type { RunConfigFormValues, RunConfigProvider, RunReasoningEffort } from '#/lib/run-config'
import { createRunConfigDraftState, runConfigDraftReducer } from '#/lib/run-config-draft'
import { cn } from '#/lib/utils'

type NewRunDialogProps = {
  agent: AgentInstance
  canSubmit: boolean
  onOpenChange: (open: boolean) => void
  onSubmit: (runConfigYaml: string) => Promise<void>
  open: boolean
}

type RunNameMode = 'autogenerated' | 'custom'

const selectClassName =
  'flex h-8 w-full rounded-md border border-(--input-border) bg-(--input-bg) px-3 py-1 text-sm text-(--input-text) shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring focus-visible:ring-(--sigil-accent-focus-ring) disabled:cursor-not-allowed disabled:opacity-50'

function formatRunStartError(error: unknown): string {
  if (error instanceof AppServerRequestError) {
    const errorData = error.errorObject.data as unknown
    const domainError =
      errorData != null &&
      typeof errorData === 'object' &&
      !Array.isArray(errorData) &&
      typeof (errorData as Record<string, unknown>).error === 'string'
        ? ((errorData as Record<string, unknown>).error as string)
        : null

    return domainError ?? error.errorObject.message
  }

  if (error instanceof Error && error.message.trim().length > 0) {
    return error.message
  }

  return 'Failed to start run.'
}

function Field({ children, label }: { children: ReactNode; label: ReactNode }) {
  return (
    <div className="flex flex-col gap-1.5 text-xs font-semibold text-muted-foreground">
      <span className="tracking-[0.14em] uppercase">{label}</span>
      {children}
    </div>
  )
}

function ToggleField({
  checked,
  children,
  dataTestId,
  onChange,
}: {
  checked: boolean
  children: ReactNode
  dataTestId: string
  onChange: (checked: boolean) => void
}) {
  return (
    <label className="flex items-center gap-2 text-sm font-medium text-foreground">
      <input
        data-testid={dataTestId}
        type="checkbox"
        checked={checked}
        onChange={(event) => onChange(event.target.checked)}
        className="size-3.5 rounded border-(--input-border)"
      />
      {children}
    </label>
  )
}

export function NewRunDialog({ agent, canSubmit, onOpenChange, onSubmit, open }: NewRunDialogProps) {
  const [activeTab, setActiveTab] = useState<'form' | 'yaml'>('form')
  const [runNameMode, setRunNameMode] = useState<RunNameMode>('autogenerated')
  const [optionalSettingsOpen, setOptionalSettingsOpen] = useState(false)
  const [draft, dispatch] = useReducer(runConfigDraftReducer, undefined, () => createRunConfigDraftState())
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)

  useEffect(() => {
    if (!open) {
      return
    }

    dispatch({ type: 'RESET' })
    setActiveTab('form')
    setRunNameMode('autogenerated')
    setOptionalSettingsOpen(false)
    setIsSubmitting(false)
    setSubmitError(null)
  }, [agent.id, open])

  function updateFormValues(nextFormValues: RunConfigFormValues) {
    dispatch({
      type: 'FORM_UPDATED',
      formValues: nextFormValues,
    })
    setSubmitError(null)
  }

  function handleProviderChange(event: ChangeEvent<HTMLSelectElement>) {
    const nextProvider = event.target.value as RunConfigProvider
    updateFormValues({
      ...draft.formValues,
      llm: {
        ...draft.formValues.llm,
        provider: nextProvider,
        model: resolveModelForProvider(nextProvider, draft.formValues.llm.model),
      },
    })
  }

  function handleReasoningEffortChange(event: ChangeEvent<HTMLSelectElement>) {
    updateFormValues({
      ...draft.formValues,
      llm: {
        ...draft.formValues.llm,
        reasoning: {
          ...draft.formValues.llm.reasoning,
          effort: event.target.value as RunReasoningEffort,
        },
      },
    })
  }

  function handleRegenerateName() {
    updateFormValues({
      ...draft.formValues,
      name: createAutogeneratedRunName(),
    })
  }

  function handleCustomizeName() {
    setRunNameMode('custom')
    setSubmitError(null)
  }

  function handleUseAutogeneratedName() {
    setRunNameMode('autogenerated')
    handleRegenerateName()
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setIsSubmitting(true)
    setSubmitError(null)

    try {
      await onSubmit(draft.yamlText)
    } catch (error) {
      setActiveTab('yaml')
      setSubmitError(formatRunStartError(error))
    } finally {
      setIsSubmitting(false)
    }
  }

  const availableModels = getModelsForProvider(draft.formValues.llm.provider)
  const hasOptionalSettings = draft.formValues.systemPromptAppend.trim().length > 0

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        data-testid="new-run-dialog-content"
        className="h-[min(85vh,48rem)] gap-0 overflow-hidden border-(--line) bg-(--workspace-bg) p-0"
      >
        <div data-testid="new-run-dialog" className="flex h-full min-h-0 flex-col">
          <form onSubmit={handleSubmit} className="flex min-h-0 flex-1 flex-col">
            <Tabs
              value={activeTab}
              onValueChange={(value) => setActiveTab(value as 'form' | 'yaml')}
              className="flex min-h-0 flex-1 flex-col"
            >
              <DialogHeader className="border-b border-(--line) px-6 pt-5 pb-3">
                <div className="flex flex-col gap-3 sm:flex-row sm:items-start sm:justify-between">
                  <div>
                    <DialogTitle>New Run</DialogTitle>
                    <DialogDescription className="sr-only">
                      Configure and start a Sigil run for the selected agent.
                    </DialogDescription>
                  </div>

                  <TabsList className="h-9 w-full bg-(--surface-strong) p-1 sm:w-auto">
                    <TabsTrigger
                      data-testid="new-run-tab-form"
                      value="form"
                      className="flex-1 px-3.5 text-xs font-semibold text-muted-foreground data-[state=active]:bg-(--workspace-bg) data-[state=active]:text-foreground sm:flex-none"
                    >
                      Form
                    </TabsTrigger>
                    <TabsTrigger
                      data-testid="new-run-tab-yaml"
                      value="yaml"
                      className="flex-1 px-3.5 text-xs font-semibold text-muted-foreground data-[state=active]:bg-(--workspace-bg) data-[state=active]:text-foreground sm:flex-none"
                    >
                      YAML
                    </TabsTrigger>
                  </TabsList>
                </div>
              </DialogHeader>

              <TabsContent value="form" className="min-h-0 flex-1 overflow-hidden data-[state=inactive]:hidden">
                <ScrollArea className="h-full">
                  <div className="space-y-4 px-6 py-4">
                    <div data-testid="new-run-group-name">
                      <Field label="Run Name">
                        <div className="space-y-2.5 rounded-lg border border-(--line) bg-(--surface) p-3">
                          <div className="flex flex-col gap-2 sm:flex-row sm:items-center sm:justify-between">
                            <div className="flex min-w-0 flex-wrap items-center gap-2">
                              <Badge
                                data-testid="new-run-name-mode-badge"
                                variant={runNameMode === 'autogenerated' ? 'outline' : 'secondary'}
                                className="rounded-md px-2 py-0.5 tracking-[0.16em] uppercase"
                              >
                                {runNameMode === 'autogenerated' ? 'Auto' : 'Custom'}
                              </Badge>
                              <span className="text-[11px] font-medium text-muted-foreground">
                                {runNameMode === 'autogenerated' ? 'Generated by Sigil.' : 'Custom editing is active.'}
                              </span>
                            </div>

                            <div className="flex flex-wrap items-center gap-2">
                              {runNameMode === 'autogenerated' ? (
                                <>
                                  <Button
                                    data-testid="new-run-regenerate-name-button"
                                    type="button"
                                    variant="ghost"
                                    size="icon-xs"
                                    aria-label="Regenerate run name"
                                    title="Regenerate run name"
                                    onClick={handleRegenerateName}
                                  >
                                    <RotateCcw className="size-3" />
                                  </Button>
                                  <Button
                                    data-testid="new-run-customize-name-button"
                                    type="button"
                                    variant="toolbar"
                                    size="xs"
                                    onClick={handleCustomizeName}
                                  >
                                    Customize
                                  </Button>
                                </>
                              ) : (
                                <Button
                                  data-testid="new-run-use-autogenerated-name-button"
                                  type="button"
                                  variant="ghost"
                                  size="xs"
                                  onClick={handleUseAutogeneratedName}
                                >
                                  Use autogenerated
                                </Button>
                              )}
                            </div>
                          </div>

                          <Input
                            data-testid="new-run-input-name"
                            value={draft.formValues.name}
                            readOnly={runNameMode === 'autogenerated'}
                            onChange={(event) =>
                              updateFormValues({
                                ...draft.formValues,
                                name: event.target.value,
                              })
                            }
                            className={cn(
                              'h-10 border-(--input-border) font-mono text-sm font-semibold focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)',
                              runNameMode === 'autogenerated'
                                ? 'cursor-default border-dashed bg-(--surface-strong) text-foreground shadow-none read-only:focus-visible:ring-0'
                                : 'bg-(--input-bg) text-(--input-text)',
                            )}
                          />
                        </div>
                      </Field>
                    </div>

                    <div data-testid="new-run-group-provider-model" className="grid gap-4 md:grid-cols-2">
                      <Field label="Provider">
                        <select
                          data-testid="new-run-select-provider"
                          value={draft.formValues.llm.provider}
                          onChange={handleProviderChange}
                          className={selectClassName}
                        >
                          {RUN_PROVIDERS.map((provider) => (
                            <option key={provider} value={provider}>
                              {provider}
                            </option>
                          ))}
                        </select>
                      </Field>

                      <Field label="Model">
                        <select
                          data-testid="new-run-select-model"
                          value={draft.formValues.llm.model}
                          onChange={(event) =>
                            updateFormValues({
                              ...draft.formValues,
                              llm: {
                                ...draft.formValues.llm,
                                model: resolveModelForProvider(draft.formValues.llm.provider, event.target.value),
                              },
                            })
                          }
                          className={selectClassName}
                        >
                          {availableModels.map((model) => (
                            <option key={model} value={model}>
                              {model}
                            </option>
                          ))}
                        </select>
                      </Field>
                    </div>

                    <div className="grid gap-4 md:grid-cols-2">
                      <section data-testid="new-run-group-reasoning" className="space-y-3">
                        <div className="space-y-2">
                          <span className="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
                            Reasoning
                          </span>
                          <ToggleField
                            dataTestId="new-run-checkbox-reasoning-enabled"
                            checked={draft.formValues.llm.reasoning.enabled}
                            onChange={(checked) =>
                              updateFormValues({
                                ...draft.formValues,
                                llm: {
                                  ...draft.formValues.llm,
                                  reasoning: {
                                    ...draft.formValues.llm.reasoning,
                                    enabled: checked,
                                  },
                                },
                              })
                            }
                          >
                            Enable Reasoning
                          </ToggleField>
                        </div>

                        <div
                          className={cn(
                            'space-y-2 rounded-lg border border-(--line) bg-(--surface) px-3 py-3 transition-opacity',
                            !draft.formValues.llm.reasoning.enabled && 'opacity-70',
                          )}
                        >
                          <Field label="Reasoning Effort">
                            <select
                              data-testid="new-run-select-reasoning-effort"
                              value={draft.formValues.llm.reasoning.effort}
                              disabled={!draft.formValues.llm.reasoning.enabled}
                              onChange={handleReasoningEffortChange}
                              className={selectClassName}
                            >
                              {RUN_REASONING_EFFORTS.map((effort) => (
                                <option key={effort} value={effort}>
                                  {effort}
                                </option>
                              ))}
                            </select>
                          </Field>
                          <p className="text-[11px] font-medium text-muted-foreground">
                            Available when reasoning is enabled.
                          </p>
                        </div>
                      </section>

                      <section data-testid="new-run-group-rlm" className="space-y-3">
                        <div className="space-y-2">
                          <span className="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
                            RLM
                          </span>
                          <ToggleField
                            dataTestId="new-run-checkbox-rlm-enabled"
                            checked={draft.formValues.rlm.enabled}
                            onChange={(checked) =>
                              updateFormValues({
                                ...draft.formValues,
                                rlm: {
                                  ...draft.formValues.rlm,
                                  enabled: checked,
                                },
                              })
                            }
                          >
                            Enable RLM
                          </ToggleField>
                        </div>

                        <div
                          className={cn(
                            'space-y-2 rounded-lg border border-(--line) bg-(--surface) px-3 py-3 transition-opacity',
                            !draft.formValues.rlm.enabled && 'opacity-70',
                          )}
                        >
                          <Field label="RLM Depth">
                            <Input
                              data-testid="new-run-input-rlm-max-depth"
                              type="number"
                              min={1}
                              step={1}
                              disabled={!draft.formValues.rlm.enabled}
                              value={String(draft.formValues.rlm.maxDepth)}
                              onChange={(event) => {
                                const parsedValue = Number.parseInt(event.target.value, 10)
                                updateFormValues({
                                  ...draft.formValues,
                                  rlm: {
                                    ...draft.formValues.rlm,
                                    maxDepth: Number.isFinite(parsedValue) && parsedValue > 0 ? parsedValue : 1,
                                  },
                                })
                              }}
                              className="h-8 border-(--input-border) bg-(--input-bg) text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                            />
                          </Field>
                          <p className="text-[11px] font-medium text-muted-foreground">
                            Controls how many recursive RLM expansions this run can take.
                          </p>
                        </div>
                      </section>
                    </div>

                    <Field label="Prompt">
                      <Textarea
                        data-testid="new-run-textarea-prompt"
                        value={draft.formValues.prompt}
                        onChange={(event) =>
                          updateFormValues({
                            ...draft.formValues,
                            prompt: event.target.value,
                          })
                        }
                        placeholder="Describe the operator request for this run."
                        className="min-h-24 border-(--input-border) bg-(--input-bg) text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                      />
                    </Field>

                    <Field
                      label={
                        <>
                          Context{' '}
                          <span className="text-[10px] font-medium tracking-normal text-muted-foreground/80 normal-case">
                            (required)
                          </span>
                        </>
                      }
                    >
                      <div className="space-y-2">
                        <Textarea
                          data-testid="new-run-textarea-context"
                          value={draft.formValues.context}
                          onChange={(event) =>
                            updateFormValues({
                              ...draft.formValues,
                              context: event.target.value,
                            })
                          }
                          placeholder="Context that the prompt request will use"
                          className="min-h-24 border-(--input-border) bg-(--input-bg) font-mono text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                        />
                        <p className="text-[11px] font-medium text-muted-foreground">
                          Provide the external context the Sigil harness will use for this run.
                        </p>
                      </div>
                    </Field>

                    <div
                      data-testid="new-run-optional-settings"
                      className={cn(
                        'rounded-lg border border-dashed border-(--line) bg-(--surface)/70',
                        hasOptionalSettings && 'border-(--sigil-accent-focus-border)',
                      )}
                    >
                      <button
                        data-testid="new-run-optional-settings-toggle"
                        type="button"
                        className="flex w-full items-center justify-between gap-3 px-4 py-3 text-left"
                        aria-expanded={optionalSettingsOpen}
                        onClick={() => setOptionalSettingsOpen((openState) => !openState)}
                      >
                        <div className="space-y-1">
                          <div className="flex flex-wrap items-center gap-2">
                            <div className="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
                              Optional Settings
                            </div>
                            {hasOptionalSettings ? (
                              <Badge
                                variant="secondary"
                                className="rounded-md px-2 py-0.5 text-[10px] tracking-[0.12em] uppercase"
                              >
                                Configured
                              </Badge>
                            ) : null}
                          </div>
                          <div className="text-xs text-muted-foreground">Future non-core run inputs live here.</div>
                        </div>
                        <ChevronDown
                          className={cn(
                            'size-4 text-muted-foreground transition-transform',
                            optionalSettingsOpen ? 'rotate-180' : 'rotate-0',
                          )}
                        />
                      </button>

                      {optionalSettingsOpen ? (
                        <div
                          data-testid="new-run-optional-settings-panel"
                          className="border-t border-(--line) px-4 py-4"
                        >
                          <Field
                            label={
                              <>
                                System Prompt Append{' '}
                                <span className="text-[10px] font-medium tracking-normal text-muted-foreground/80 normal-case">
                                  (optional)
                                </span>
                              </>
                            }
                          >
                            <Textarea
                              data-testid="new-run-textarea-system-prompt-append"
                              value={draft.formValues.systemPromptAppend}
                              onChange={(event) =>
                                updateFormValues({
                                  ...draft.formValues,
                                  systemPromptAppend: event.target.value,
                                })
                              }
                              placeholder="Add instructions to the base System Prompt"
                              className="min-h-20 border-(--input-border) bg-(--input-bg) text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                            />
                          </Field>
                        </div>
                      ) : null}
                    </div>
                  </div>
                </ScrollArea>
              </TabsContent>

              <TabsContent
                value="yaml"
                className="flex min-h-0 flex-1 flex-col overflow-hidden px-6 py-5 data-[state=inactive]:hidden"
              >
                <div className="mb-3 flex items-center justify-between gap-3">
                  <div className="text-xs text-muted-foreground">
                    {draft.yamlMode === 'manual'
                      ? 'Manual YAML mode is active. Form edits will not overwrite the textarea until you reset it.'
                      : 'Generated YAML stays synchronized with the form until you edit it manually.'}
                  </div>
                  <Button
                    data-testid="new-run-reset-yaml-button"
                    type="button"
                    variant="ghost"
                    size="xs"
                    disabled={draft.yamlMode !== 'manual'}
                    onClick={() => {
                      dispatch({ type: 'RESET_YAML_FROM_FORM' })
                      setSubmitError(null)
                    }}
                  >
                    <RotateCcw className="size-3" />
                    Reset YAML from form
                  </Button>
                </div>

                <Textarea
                  data-testid="new-run-textarea-yaml"
                  value={draft.yamlText}
                  onChange={(event) => {
                    dispatch({
                      type: 'YAML_UPDATED',
                      yamlText: event.target.value,
                    })
                    setSubmitError(null)
                  }}
                  className="min-h-0 flex-1 border-(--input-border) bg-(--input-bg) font-mono text-xs leading-5 text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                />
              </TabsContent>
            </Tabs>

            <div className="border-t border-(--line) px-6 py-4">
              {!canSubmit ? (
                <div data-testid="new-run-submit-disabled-reason" className="mb-3 text-sm text-muted-foreground">
                  Agent connection must be ready before starting a run.
                </div>
              ) : null}

              {submitError ? (
                <div
                  data-testid="new-run-inline-error"
                  className="mb-3 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"
                >
                  {submitError}
                </div>
              ) : null}

              <DialogFooter>
                <Button
                  data-testid="new-run-cancel-button"
                  type="button"
                  variant="ghost"
                  onClick={() => onOpenChange(false)}
                >
                  Cancel
                </Button>
                <Button
                  data-testid="new-run-submit-button"
                  type="submit"
                  variant="accent"
                  disabled={!canSubmit || isSubmitting}
                >
                  {isSubmitting ? (
                    <>
                      <LoaderCircle className="size-3 animate-spin" />
                      Starting...
                    </>
                  ) : (
                    'Start Run'
                  )}
                </Button>
              </DialogFooter>
            </div>
          </form>
        </div>
      </DialogContent>
    </Dialog>
  )
}
