import { useEffect, useReducer, useState } from 'react'
import type { ChangeEvent, FormEvent, ReactNode } from 'react'
import { ChevronDown, LoaderCircle, Pencil, RotateCcw, XIcon } from 'lucide-react'
import { Badge } from '#/components/ui/badge'
import { Button } from '#/components/ui/button'
import {
  Dialog,
  DialogClose,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
} from '#/components/ui/dialog'
import { Input } from '#/components/ui/input'
import { ScrollArea } from '#/components/ui/scroll-area'
import { Tabs, TabsContent, TabsList, TabsTrigger } from '#/components/ui/tabs'
import { Textarea } from '#/components/ui/textarea'
import type { AgentInstance } from '#/lib/demo-data'
import { AppServerRequestError } from '#/lib/appserver/client'
import {
  RUN_PROVIDERS,
  RUN_REASONING_EFFORTS,
  createAutogeneratedRunName,
  getModelsForProvider,
  resolveModelForProvider,
} from '#/lib/run-config'
import type { RunConfigFormValues, RunConfigProvider, RunReasoningEffort } from '#/lib/run-config'
import { createRunConfigDraftState, runConfigDraftReducer } from '#/lib/run-config-draft'
import { cn } from '#/lib/utils'

type NewRunDialogProps = {
  agent: AgentInstance
  canSubmit: boolean
  onOpenChange: (open: boolean) => void
  onSubmit: (runConfigYaml: string) => Promise<void>
  open: boolean
}

type RunNameMode = 'autogenerated' | 'custom'

const selectClassName =
  'flex h-8 w-full appearance-none rounded-md border border-(--input-border) bg-(--input-bg) px-3 py-1 pr-8 text-sm text-(--input-text) shadow-xs transition-[color,box-shadow] outline-none focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring focus-visible:ring-(--sigil-accent-focus-ring) disabled:cursor-not-allowed disabled:opacity-50'

function formatRunStartError(error: unknown): string {
  if (error instanceof AppServerRequestError) {
    const errorData = error.errorObject.data as unknown
    const domainError =
      errorData != null &&
      typeof errorData === 'object' &&
      !Array.isArray(errorData) &&
      typeof (errorData as Record<string, unknown>).error === 'string'
        ? ((errorData as Record<string, unknown>).error as string)
        : null

    return domainError ?? error.errorObject.message
  }

  if (error instanceof Error && error.message.trim().length > 0) {
    return error.message
  }

  return 'Failed to start run.'
}

function Field({ children, label }: { children: ReactNode; label: ReactNode }) {
  return (
    <div className="flex flex-col gap-1.5 text-xs font-semibold text-muted-foreground">
      <span className="tracking-[0.14em] uppercase">{label}</span>
      {children}
    </div>
  )
}

function ToggleField({
  checked,
  children,
  dataTestId,
  onChange,
}: {
  checked: boolean
  children: ReactNode
  dataTestId: string
  onChange: (checked: boolean) => void
}) {
  return (
    <label className="flex items-center gap-2 text-sm font-medium text-foreground">
      <input
        data-testid={dataTestId}
        type="checkbox"
        checked={checked}
        onChange={(event) => onChange(event.target.checked)}
        className="size-3.5 rounded border-(--input-border)"
      />
      {children}
    </label>
  )
}

function SelectField({ children, className, ...props }: React.ComponentProps<'select'>) {
  return (
    <div className="relative">
      <select {...props} className={cn(selectClassName, className)}>
        {children}
      </select>
      <ChevronDown className="pointer-events-none absolute top-1/2 right-2 size-4 -translate-y-1/2 text-muted-foreground" />
    </div>
  )
}

export function NewRunDialog({ agent, canSubmit, onOpenChange, onSubmit, open }: NewRunDialogProps) {
  const [activeTab, setActiveTab] = useState<'form' | 'yaml'>('form')
  const [runNameMode, setRunNameMode] = useState<RunNameMode>('autogenerated')
  const [advancedSettingsOpen, setAdvancedSettingsOpen] = useState(false)
  const [draft, dispatch] = useReducer(runConfigDraftReducer, undefined, () => createRunConfigDraftState())
  const [isSubmitting, setIsSubmitting] = useState(false)
  const [submitError, setSubmitError] = useState<string | null>(null)

  useEffect(() => {
    if (!open) {
      return
    }

    dispatch({ type: 'RESET' })
    setActiveTab('form')
    setRunNameMode('autogenerated')
    setAdvancedSettingsOpen(false)
    setIsSubmitting(false)
    setSubmitError(null)
  }, [agent.id, open])

  function updateFormValues(nextFormValues: RunConfigFormValues) {
    dispatch({
      type: 'FORM_UPDATED',
      formValues: nextFormValues,
    })
    setSubmitError(null)
  }

  function handleProviderChange(event: ChangeEvent<HTMLSelectElement>) {
    const nextProvider = event.target.value as RunConfigProvider
    updateFormValues({
      ...draft.formValues,
      llm: {
        ...draft.formValues.llm,
        provider: nextProvider,
        model: resolveModelForProvider(nextProvider, draft.formValues.llm.model),
      },
    })
  }

  function handleReasoningEffortChange(event: ChangeEvent<HTMLSelectElement>) {
    updateFormValues({
      ...draft.formValues,
      llm: {
        ...draft.formValues.llm,
        reasoning: {
          ...draft.formValues.llm.reasoning,
          effort: event.target.value as RunReasoningEffort,
        },
      },
    })
  }

  function handleRegenerateName() {
    updateFormValues({
      ...draft.formValues,
      name: createAutogeneratedRunName(),
    })
  }

  function handleCustomizeName() {
    setRunNameMode('custom')
    setSubmitError(null)
  }

  function handleUseAutogeneratedName() {
    setRunNameMode('autogenerated')
    handleRegenerateName()
  }

  async function handleSubmit(event: FormEvent<HTMLFormElement>) {
    event.preventDefault()
    setIsSubmitting(true)
    setSubmitError(null)

    try {
      await onSubmit(draft.yamlText)
    } catch (error) {
      setActiveTab('yaml')
      setSubmitError(formatRunStartError(error))
    } finally {
      setIsSubmitting(false)
    }
  }

  const availableModels = getModelsForProvider(draft.formValues.llm.provider)
  const hasAdvancedSettings = draft.formValues.systemPromptAppend.trim().length > 0

  return (
    <Dialog open={open} onOpenChange={onOpenChange}>
      <DialogContent
        data-testid="new-run-dialog-content"
        showClose={false}
        className="h-[min(85vh,40rem)] w-[min(calc(100vw-2rem),48rem)] gap-0 overflow-hidden border-(--line) bg-(--workspace-bg) p-0"
      >
        <div data-testid="new-run-dialog" className="flex h-full min-h-0 flex-col">
          <form onSubmit={handleSubmit} className="flex min-h-0 flex-1 flex-col">
            <Tabs
              value={activeTab}
              onValueChange={(value) => setActiveTab(value as 'form' | 'yaml')}
              className="flex min-h-0 flex-1 flex-col"
            >
              <DialogHeader className="border-b border-(--line) px-4 py-3">
                <div className="flex items-center">
                  <DialogTitle className="flex-1 pl-2">New Run</DialogTitle>
                  <DialogDescription className="sr-only">
                    Configure and start a Sigil run for the selected agent.
                  </DialogDescription>

                  <TabsList className="h-9 bg-(--surface-strong) p-1">
                    <TabsTrigger
                      data-testid="new-run-tab-form"
                      value="form"
                      className="px-3.5 text-xs font-semibold text-muted-foreground data-[state=active]:bg-(--workspace-bg) data-[state=active]:text-foreground"
                    >
                      Form
                    </TabsTrigger>
                    <TabsTrigger
                      data-testid="new-run-tab-yaml"
                      value="yaml"
                      className="px-3.5 text-xs font-semibold text-muted-foreground data-[state=active]:bg-(--workspace-bg) data-[state=active]:text-foreground"
                    >
                      YAML
                    </TabsTrigger>
                  </TabsList>

                  <div className="flex flex-1 justify-end pr-2">
                    <DialogClose className="rounded-sm opacity-70 transition-opacity hover:opacity-100 focus-visible:ring focus-visible:ring-ring/50 focus-visible:outline-none">
                      <XIcon className="size-4" />
                      <span className="sr-only">Close</span>
                    </DialogClose>
                  </div>
                </div>
              </DialogHeader>

              <TabsContent value="form" className="min-h-0 flex-1 overflow-hidden data-[state=inactive]:hidden">
                <ScrollArea className="h-full">
                  <div className="space-y-3 px-6 py-4">
                    <div data-testid="new-run-group-name" className="flex flex-col gap-1.5">
                      <span className="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
                        Run Name
                      </span>
                      {runNameMode === 'autogenerated' ? (
                        <div className="flex items-center gap-1.5">
                          <Input
                            data-testid="new-run-input-name"
                            value={draft.formValues.name}
                            readOnly
                            tabIndex={-1}
                            className="h-8 flex-1 cursor-default border-transparent bg-transparent font-mono text-sm font-semibold text-foreground shadow-none read-only:focus-visible:ring-0"
                          />
                          <Badge
                            data-testid="new-run-name-mode-badge"
                            variant="outline"
                            className="rounded-md px-2 py-0.5 text-[10px] tracking-[0.16em] uppercase"
                          >
                            Auto
                          </Badge>
                          <Button
                            data-testid="new-run-regenerate-name-button"
                            type="button"
                            variant="ghost"
                            size="icon-xs"
                            aria-label="Regenerate run name"
                            title="Regenerate run name"
                            onClick={handleRegenerateName}
                          >
                            <RotateCcw className="size-3" />
                          </Button>
                          <Button
                            data-testid="new-run-customize-name-button"
                            type="button"
                            variant="ghost"
                            size="icon-xs"
                            aria-label="Customize run name"
                            title="Customize run name"
                            onClick={handleCustomizeName}
                          >
                            <Pencil className="size-3" />
                          </Button>
                        </div>
                      ) : (
                        <div className="flex items-center gap-1.5">
                          <Input
                            data-testid="new-run-input-name"
                            value={draft.formValues.name}
                            onChange={(event) =>
                              updateFormValues({
                                ...draft.formValues,
                                name: event.target.value,
                              })
                            }
                            className="h-8 flex-1 border-(--input-border) bg-(--input-bg) font-mono text-sm font-semibold text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                          />
                          <Badge
                            data-testid="new-run-name-mode-badge"
                            variant="secondary"
                            className="rounded-md px-2 py-0.5 text-[10px] tracking-[0.16em] uppercase"
                          >
                            Custom
                          </Badge>
                          <Button
                            data-testid="new-run-use-autogenerated-name-button"
                            type="button"
                            variant="ghost"
                            size="icon-xs"
                            aria-label="Use autogenerated name"
                            title="Use autogenerated name"
                            onClick={handleUseAutogeneratedName}
                          >
                            <RotateCcw className="size-3" />
                          </Button>
                        </div>
                      )}
                    </div>

                    <Field label="Prompt">
                      <Textarea
                        data-testid="new-run-textarea-prompt"
                        value={draft.formValues.prompt}
                        onChange={(event) =>
                          updateFormValues({
                            ...draft.formValues,
                            prompt: event.target.value,
                          })
                        }
                        placeholder="Describe the operator request for this run."
                        className="min-h-24 border-(--input-border) bg-(--input-bg) text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                      />
                    </Field>

                    <Field
                      label={
                        <>
                          Context{' '}
                          <span className="text-[10px] font-medium tracking-normal text-muted-foreground/80 normal-case">
                            (required)
                          </span>
                        </>
                      }
                    >
                      <Textarea
                        data-testid="new-run-textarea-context"
                        value={draft.formValues.context}
                        onChange={(event) =>
                          updateFormValues({
                            ...draft.formValues,
                            context: event.target.value,
                          })
                        }
                        placeholder="Context that the prompt request will use"
                        className="min-h-24 border-(--input-border) bg-(--input-bg) font-mono text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                      />
                    </Field>

                    <div data-testid="new-run-group-model-config" className="flex flex-col gap-1.5">
                      <span className="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
                        Model Configuration
                      </span>

                      <div className="space-y-3 rounded-lg border border-(--line) bg-(--surface)/50 px-4 py-3">
                        <div data-testid="new-run-group-provider-model" className="grid gap-3 md:grid-cols-2">
                          <Field label="Provider">
                            <SelectField
                              data-testid="new-run-select-provider"
                              value={draft.formValues.llm.provider}
                              onChange={handleProviderChange}
                            >
                              {RUN_PROVIDERS.map((provider) => (
                                <option key={provider} value={provider}>
                                  {provider}
                                </option>
                              ))}
                            </SelectField>
                          </Field>

                          <Field label="Model">
                            <SelectField
                              data-testid="new-run-select-model"
                              value={draft.formValues.llm.model}
                              onChange={(event) =>
                                updateFormValues({
                                  ...draft.formValues,
                                  llm: {
                                    ...draft.formValues.llm,
                                    model: resolveModelForProvider(draft.formValues.llm.provider, event.target.value),
                                  },
                                })
                              }
                            >
                              {availableModels.map((model) => (
                                <option key={model} value={model}>
                                  {model}
                                </option>
                              ))}
                            </SelectField>
                          </Field>
                        </div>

                        <div className="grid gap-3 md:grid-cols-2">
                          <div
                            data-testid="new-run-group-reasoning"
                            className={cn(
                              'flex items-center gap-3 transition-opacity',
                              !draft.formValues.llm.reasoning.enabled && 'opacity-50',
                            )}
                          >
                            <ToggleField
                              dataTestId="new-run-checkbox-reasoning-enabled"
                              checked={draft.formValues.llm.reasoning.enabled}
                              onChange={(checked) =>
                                updateFormValues({
                                  ...draft.formValues,
                                  llm: {
                                    ...draft.formValues.llm,
                                    reasoning: {
                                      ...draft.formValues.llm.reasoning,
                                      enabled: checked,
                                    },
                                  },
                                })
                              }
                            >
                              Reasoning
                            </ToggleField>
                            <SelectField
                              data-testid="new-run-select-reasoning-effort"
                              value={draft.formValues.llm.reasoning.effort}
                              disabled={!draft.formValues.llm.reasoning.enabled}
                              onChange={handleReasoningEffortChange}
                              className="w-28"
                            >
                              {RUN_REASONING_EFFORTS.map((effort) => (
                                <option key={effort} value={effort}>
                                  {effort}
                                </option>
                              ))}
                            </SelectField>
                          </div>

                          <div
                            data-testid="new-run-group-rlm"
                            className={cn(
                              'flex items-center gap-3 transition-opacity',
                              !draft.formValues.rlm.enabled && 'opacity-50',
                            )}
                          >
                            <ToggleField
                              dataTestId="new-run-checkbox-rlm-enabled"
                              checked={draft.formValues.rlm.enabled}
                              onChange={(checked) =>
                                updateFormValues({
                                  ...draft.formValues,
                                  rlm: {
                                    ...draft.formValues.rlm,
                                    enabled: checked,
                                  },
                                })
                              }
                            >
                              RLM
                            </ToggleField>
                            <Input
                              data-testid="new-run-input-rlm-max-depth"
                              type="number"
                              min={1}
                              step={1}
                              disabled={!draft.formValues.rlm.enabled}
                              value={String(draft.formValues.rlm.maxDepth)}
                              onChange={(event) => {
                                const parsedValue = Number.parseInt(event.target.value, 10)
                                updateFormValues({
                                  ...draft.formValues,
                                  rlm: {
                                    ...draft.formValues.rlm,
                                    maxDepth: Number.isFinite(parsedValue) && parsedValue > 0 ? parsedValue : 1,
                                  },
                                })
                              }}
                              className="h-8 w-20 border-(--input-border) bg-(--input-bg) text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                            />
                          </div>
                        </div>
                      </div>
                    </div>

                    <div data-testid="new-run-advanced-settings" className="flex flex-col gap-1.5">
                      <div className="flex items-center gap-2">
                        <span className="text-xs font-semibold tracking-[0.14em] text-muted-foreground uppercase">
                          Advanced Settings
                        </span>
                        {hasAdvancedSettings ? (
                          <Badge
                            variant="secondary"
                            className="rounded-md px-2 py-0.5 text-[10px] tracking-[0.12em] uppercase"
                          >
                            Configured
                          </Badge>
                        ) : null}
                      </div>
                      <div
                        className={cn(
                          'rounded-lg border border-dashed border-(--line) bg-(--surface)/70',
                          hasAdvancedSettings && 'border-(--sigil-accent-focus-border)',
                        )}
                      >
                        <button
                          data-testid="new-run-advanced-settings-toggle"
                          type="button"
                          className="flex w-full items-center justify-between gap-3 px-4 py-2.5 text-left"
                          aria-expanded={advancedSettingsOpen}
                          onClick={() => setAdvancedSettingsOpen((openState) => !openState)}
                        >
                          <span className="text-xs text-muted-foreground">
                            System prompt customization and additional overrides.
                          </span>
                          <ChevronDown
                            className={cn(
                              'size-4 shrink-0 text-muted-foreground transition-transform',
                              advancedSettingsOpen ? 'rotate-180' : 'rotate-0',
                            )}
                          />
                        </button>

                        {advancedSettingsOpen ? (
                          <div
                            data-testid="new-run-advanced-settings-panel"
                            className="border-t border-(--line) px-4 py-4"
                          >
                            <Field
                              label={
                                <>
                                  System Prompt Append{' '}
                                  <span className="text-[10px] font-medium tracking-normal text-muted-foreground/80 normal-case">
                                    (optional)
                                  </span>
                                </>
                              }
                            >
                              <Textarea
                                data-testid="new-run-textarea-system-prompt-append"
                                value={draft.formValues.systemPromptAppend}
                                onChange={(event) =>
                                  updateFormValues({
                                    ...draft.formValues,
                                    systemPromptAppend: event.target.value,
                                  })
                                }
                                placeholder="Add instructions to the base System Prompt"
                                className="min-h-20 border-(--input-border) bg-(--input-bg) text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                              />
                            </Field>
                          </div>
                        ) : null}
                      </div>
                    </div>
                  </div>
                </ScrollArea>
              </TabsContent>

              <TabsContent
                value="yaml"
                className="flex min-h-0 flex-1 flex-col overflow-hidden px-6 py-5 data-[state=inactive]:hidden"
              >
                <div className="mb-3 flex items-center justify-between gap-3">
                  <div className="text-xs text-muted-foreground">
                    {draft.yamlMode === 'manual'
                      ? 'Manual YAML mode is active. Form edits will not overwrite the textarea until you reset it.'
                      : 'Generated YAML stays synchronized with the form until you edit it manually.'}
                  </div>
                  <Button
                    data-testid="new-run-reset-yaml-button"
                    type="button"
                    variant="ghost"
                    size="xs"
                    disabled={draft.yamlMode !== 'manual'}
                    onClick={() => {
                      dispatch({ type: 'RESET_YAML_FROM_FORM' })
                      setSubmitError(null)
                    }}
                  >
                    <RotateCcw className="size-3" />
                    Reset YAML from form
                  </Button>
                </div>

                <Textarea
                  data-testid="new-run-textarea-yaml"
                  value={draft.yamlText}
                  onChange={(event) => {
                    dispatch({
                      type: 'YAML_UPDATED',
                      yamlText: event.target.value,
                    })
                    setSubmitError(null)
                  }}
                  className="min-h-0 flex-1 border-(--input-border) bg-(--input-bg) font-mono text-xs leading-5 text-(--input-text) focus-visible:border-(--sigil-accent-focus-border) focus-visible:ring-(--sigil-accent-focus-ring)"
                />
              </TabsContent>
            </Tabs>

            <div className="border-t border-(--line) px-6 py-4">
              {!canSubmit ? (
                <div data-testid="new-run-submit-disabled-reason" className="mb-3 text-sm text-muted-foreground">
                  Agent connection must be ready before starting a run.
                </div>
              ) : null}

              {submitError ? (
                <div
                  data-testid="new-run-inline-error"
                  className="mb-3 rounded-lg border border-destructive/30 bg-destructive/10 px-3 py-2 text-sm text-destructive"
                >
                  {submitError}
                </div>
              ) : null}

              <DialogFooter>
                <Button
                  data-testid="new-run-cancel-button"
                  type="button"
                  variant="ghost"
                  onClick={() => onOpenChange(false)}
                >
                  Cancel
                </Button>
                <Button
                  data-testid="new-run-submit-button"
                  type="submit"
                  variant="accent"
                  disabled={!canSubmit || isSubmitting}
                >
                  {isSubmitting ? (
                    <>
                      <LoaderCircle className="size-3 animate-spin" />
                      Starting...
                    </>
                  ) : (
                    'Start Run'
                  )}
                </Button>
              </DialogFooter>
            </div>
          </form>
        </div>
      </DialogContent>
    </Dialog>
  )
}
